
# # STATION_CHOICES = [
# #     ("CHITTOOR", "CHITTOOR"),
# #     ("THATITHAPU", "THATITHAPU"),
# #     ("PELLAKUR", "PELLAKUR"),
# #     ("TSUNDUPALLE", "TSUNDUPALLE"),
# #     ("CHILLAKUR", "CHILLAKUR"),
# #     ("GUMMAGATTA", "GUMMAGATTA"),
# #     ("KALUVOYA", "KALUVOYA"),
# #     ("ATLUR", "ATLUR"),
# #     ("GARLADINNE", "GARLADINNE"),
# #     ("KODUR", "KODUR"),
# #     ("VIDAPANAKAL", "VIDAPANAKAL"),
# #     ("VALETIVARIPALEM", "VALETIVARIPALEM"),
# #     ("RUDRAVARAM", "RUDRAVARAM"),
# #     ("PATTIKONDA", "PATTIKONDA"),
# #     ("ADONI", "ADONI"),
# #     ("VELDHURTHY", "VELDHURTHY"),
# #     ("MANGALAGIRI", "MANGALAGIRI"),
# #     ("SANATHNAGAR", "SANATHNAGAR"),
# #     ("THULLUR", "THULLUR"),
# #     ("KROSUR", "KROSUR"),
# #     ("GOLLAPUDI", "GOLLAPUDI"),
# #     ("KOYYALAGUDEM", "KOYYALAGUDEM"),
# #     ("PETTUGOLLAPALLE", "PETTUGOLLAPALLE"),
# #     ("ADDATEEGALA", "ADDATEEGALA"),
# #     ("MAREDUMILLI", "MAREDUMILLI"),
# #     ("GANGAVARAM", "GANGAVARAM"),
# #     ("MVPCOLONY", "MVPCOLONY"),
# #     ("VISHAKHAPATTANAM", "VISHAKHAPATTANAM"),
# #     ("CHINTAPALLI", "CHINTAPALLI"),
# #     ("SRIKAKULAM", "SRIKAKULAM"),
# #     ("PARVATIPURAM", "PARVATIPURAM"),
# #     ("PANGCHAO", "PANGCHAO"),
# #     ("VIJOYNAGAR", "VIJOYNAGAR"),
# #     ("NAMPONG", "NAMPONG"),
# #     ("LADAHQ", "LADAHQ"),
# #     ("CHAYANGTAJO", "CHAYANGTAJO"),
# #     ("PASIGHAT", "PASIGHAT"),
# #     ("LONGDING KOLING HQ", "LONGDING KOLING HQ"),
# #     ("CHAGLAGAM", "CHAGLAGAM"),
# #     ("LIMEKINGH.Q", "LIMEKINGH.Q"),
# #     ("KARGONG", "KARGONG"),
# #     ("PIDI", "PIDI"),
# #     ("ANINI", "ANINI"),
# #     ("SINGA", "SINGA"),
# #     ("KARIMGANJ", "KARIMGANJ"),
# #     ("JALUKBARI", "JALUKBARI"),
# #     ("GOALPARA", "GOALPARA"),
# #     ("PANIKHAITI", "PANIKHAITI"),
# #     ("KHANABARIANIANI", "KHANABARIANIANI"),
# #     ("BARGAON", "BARGAON"),
# #     ("BARKHOPA", "BARKHOPA"),
# #     ("UDHIYAGURI", "UDHIYAGURI"),
# #     ("BISWANATHCIRCLE", "BISWANATHCIRCLE"),
# #     ("JORHAT", "JORHAT"),
# #     ("DEMOW", "DEMOW"),
# #     ("TETARIYAKHURD", "TETARIYAKHURD"),
# #     ("CHAKAI", "CHAKAI"),
# #     ("RAFIGANJ", "RAFIGANJ"),
# #     ("BHAGALPUR", "BHAGALPUR"),
# #     ("AHMADABAD", "AHMADABAD"),
# #     ("RAWAICH", "RAWAICH"),
# #     ("AZAMNAGAR", "AZAMNAGAR"),
# #     ("MARUUFGANJ", "MARUUFGANJ"),
# #     ("ROUN", "ROUN"),
# #     ("DIGHA", "DIGHA"),
# #     ("MANORI", "MANORI"),
# #     ("KUKRAUN", "KUKRAUN"),
# #     ("CHHITWARAKAPUR", "CHHITWARAKAPUR"),
# #     ("BAISI", "BAISI"),
# #     ("LAHERIASARAI", "LAHERIASARAI"),
# #     ("KURSAKATTA", "KURSAKATTA"),
# #     ("ASHOGI", "ASHOGI"),
# #     ("PURBIKARGAHIA", "PURBIKARGAHIA"),
# #     ("SONBARSA", "SONBARSA"),
# #     ("NAURANGIA", "NAURANGIA"),
# #     ("MADHYAMARG", "MADHYAMARG"),
# #     ("KIRANDUL", "KIRANDUL"),
# #     ("METAPAL", "METAPAL"),
# #     ("UTLA", "UTLA"),
# #     ("BENIDHARAUR", "BENIDHARAUR"),
# #     ("ROTAD", "ROTAD"),
# #     ("VISHRAMPURI", "VISHRAMPURI"),
# #     ("ANTAGARH", "ANTAGARH"),
# #     ("BHANUPRATAPPUR", "BHANUPRATAPPUR"),
# #     ("NAGRI", "NAGRI"),
# #     ("KHADGAON", "KHADGAON"),
# #     ("PIPARCHHEDI", "PIPARCHHEDI"),
# #     ("ATALNAGAR-NAVA", "ATALNAGAR-NAVA"),
# #     ("PITHORA", "PITHORA"),
# #     ("BIRGOAN", "BIRGOAN"),
# #     ("KHAIRAHA", "KHAIRAHA"),
# #     ("GUNARBAD", "GUNARBAD"),
# #     ("DABHARA", "DABHARA"),
# #     ("KHADI", "KHADI"),
# #     ("NAWAGARH", "NAWAGARH"),
# #     ("BALODA", "BALODA"),
# #     ("PALI", "PALI"),
# #     ("SHAHPUR", "SHAHPUR"),
# #     ("KORBI", "KORBI"),
# #     ("JHIRMITI", "JHIRMITI"),
# #     ("KELHARI", "KELHARI"),
# #     ("SINDHOR", "SINDHOR"),
# #     ("RAMANUJGANJ", "RAMANUJGANJ"),
# #     ("FUDAM", "FUDAM"),
# #     ("DELHI_1", "DELHI_1"),
# #     ("DELHI_2", "DELHI_2"),
# #     ("DELHI_3", "DELHI_3"),
# #     ("DELHI_4", "DELHI_4"),
# #     ("VASCODAGAMA", "VASCODAGAMA"),
# #     ("OLDGOA", "OLDGOA"),
# #     ("CALANGUTE", "CALANGUTE"),
# #     ("VERAVAL", "VERAVAL"),
# #     ("RAJULA", "RAJULA"),
# #     ("JUNAGADH", "JUNAGADH"),
# #     ("JESHAR", "JESHAR"),
# #     ("JASDAN", "JASDAN"),
# #     ("KAVANT", "KAVANT"),
# #     ("BERAJA", "BERAJA"),
# #     ("DWARKA", "DWARKA"),
# #     ("RAJKOT_1", "RAJKOT_1"),
# #     ("RAJKOT_2", "RAJKOT_2"),
# #     ("KHAMBHAT", "KHAMBHAT"),
# #     ("JODIYA", "JODIYA"),
# #     ("VEKARIYA", "VEKARIYA"),
# #     ("MUNDRA", "MUNDRA"),
# #     ("MALIA", "MALIA"),
# #     ("NAKHATRANA", "NAKHATRANA"),
# #     ("MEGHRAJ", "MEGHRAJ"),
# #     ("SAMI", "SAMI"),
# #     ("SANTALPUR", "SANTALPUR"),
# #     ("SATLASANA", "SATLASANA"),
# #     ("BHABHAR", "BHABHAR"),
# #     ("DHANERA", "DHANERA"),
# #     ("MAVSARI", "MAVSARI"),
# #     ("FARIDABAD", "FARIDABAD"),
# #     ("GURUGRAM_1", "GURUGRAM_1"),
# #     ("GURUGRAM_2", "GURUGRAM_2"),
# #     ("CHARKHIDADRI", "CHARKHIDADRI"),
# #     ("ISHARWAL", "ISHARWAL"),
# #     ("MADINA", "MADINA"),
# #     ("BHATTUMANDI", "BHATTUMANDI"),
# #     ("NARWANA", "NARWANA"),
# #     ("KARNAL_1", "KARNAL_1"),
# #     ("KARNAL_2", "KARNAL_2"),
# #     ("PEHOWA", "PEHOWA"),
# #     ("PANCHKULA", "PANCHKULA"),
# #     ("SHIMLA_1", "SHIMLA_1"),
# #     ("SHIMLA_2", "SHIMLA_2"),
# #     ("SHIMLA_3", "SHIMLA_3"),
# #     ("SOONA", "SOONA"),
# #     ("RECKONGPEO", "RECKONGPEO"),
# #     ("PUNASPA", "PUNASPA"),
# #     ("HAMIRPUR", "HAMIRPUR"),
# #     ("BANJAR", "BANJAR"),
# #     ("UPMOHALDANMOCHHE", "UPMOHALDANMOCHHE"),
# #     ("NAKO", "NAKO"),
# #     ("BARSHAINI", "BARSHAINI"),
# #     ("TABO", "TABO"),
# #     ("KAZA", "KAZA"),
# #     ("DAMPHUG", "DAMPHUG"),
# #     ("HANSA", "HANSA"),
# #     ("CHOBIA", "CHOBIA"),
# #     ("KEYLONG", "KEYLONG"),
# #     ("KUKUMSERI", "KUKUMSERI"),
# #     ("PARGHWAL", "PARGHWAL"),
# #     ("SUCHETGARH", "SUCHETGARH"),
# #     ("JAMMU", "JAMMU"),
# #     ("GULABGARH", "GULABGARH"),
# #     ("RAJOURI", "RAJOURI"),
# #     ("URI", "URI"),
# #     ("SRINAGAR", "SRINAGAR"),
# #     ("SISAI", "SISAI"),
# #     ("DUMRI", "DUMRI"),
# #     ("RANCHI_1", "RANCHI_1"),
# #     ("RANCHI_2", "RANCHI_2"),
# #     ("BISHUNPUR", "BISHUNPUR"),
# #     ("RANCHI_3", "RANCHI_3"),
# #     ("RANCHI_4", "RANCHI_4"),
# #     ("KHALARI", "KHALARI"),
# #     ("MAJHAULI", "MAJHAULI"),
# #     ("PAKURIA", "PAKURIA"),
# #     ("SATGAWAN", "SATGAWAN"),
# #     ("GUNDLUPETE", "GUNDLUPETE"),
# #     ("RAMAPURA", "RAMAPURA"),
# #     ("MAHADESHWARABETTA", "MAHADESHWARABETTA"),
# #     ("MYSURU_1", "MYSURU_1"),
# #     ("MYSURU_2", "MYSURU_2"),
# #     ("RAJAPURA", "RAJAPURA"),
# #     ("HEBBAL", "HEBBAL"),
# #     ("ARAKALAGUD", "ARAKALAGUD"),
# #     ("KONAPPANAAGRAHARA", "KONAPPANAAGRAHARA"),
# #     ("BENGALURU_1", "BENGALURU_1"),
# #     ("MANGALURU_1", "MANGALURU_1"),
# #     ("MANGALURU_2", "MANGALURU_2"),
# #     ("MANGALURU_3", "MANGALURU_3"),
# #     ("BENGALURU_2", "BENGALURU_2"),
# #     ("MANGALURU_4", "MANGALURU_4"),
# #     ("BENGALURU_3", "BENGALURU_3"),
# #     ("BENGALURU_4", "BENGALURU_4"),
# #     ("BEDISWASTE", "BEDISWASTE"),
# #     ("GADENAHALLI", "GADENAHALLI"),
# #     ("KALASA", "KALASA"),
# #     ("TUMAKURU_1", "TUMAKURU_1"),
# #     ("TUMAKURU_2", "TUMAKURU_2"),
# #     ("TUMAKURU_3", "TUMAKURU_3"),
# #     ("CHINTAMANI", "CHINTAMANI"),
# #     ("NARASIMHARAJAPURA", "NARASIMHARAJAPURA"),
# #     ("SIRA", "SIRA"),
# #     ("HOSADURGA", "HOSADURGA"),
# #     ("SHIVAMOGGA_1", "SHIVAMOGGA_1"),
# #     ("SHIVAMOGGA_2", "SHIVAMOGGA_2"),
# #     ("SHIVAMOGGA_3", "SHIVAMOGGA_3"),
# #     ("SAGARA", "SAGARA"),
# #     ("DAVANAGERE", "DAVANAGERE"),
# #     ("HAVERI", "HAVERI"),
# #     ("MUNDGOD", "MUNDGOD"),
# #     ("HUVINAHADAGALI", "HUVINAHADAGALI"),
# #     ("JOIDA", "JOIDA"),
# #     ("HUBBALLI_1", "HUBBALLI_1"),
# #     ("KURUGODU", "KURUGODU"),
# #     ("HUBBALLI_2", "HUBBALLI_2"),
# #     ("HUBBALLI_3", "HUBBALLI_3"),
# #     ("KANAKAGIRI", "KANAKAGIRI"),
# #     ("BELAGAVI_1", "BELAGAVI_1"),
# #     ("BELAGAVI_2", "BELAGAVI_2"),
# #     ("BELAGAVI_3", "BELAGAVI_3"),
# #     ("MANVI", "MANVI"),
# #     ("BAGALKOT", "BAGALKOT"),
# #     ("CHIKODI", "CHIKODI"),
# #     ("BASAVANABAGEWADI", "BASAVANABAGEWADI"),
# #     ("SHAHAPUR", "SHAHAPUR"),
# #     ("ALMEL", "ALMEL"),
# #     ("CHINCHOLI", "CHINCHOLI"),
# #     ("ALAND", "ALAND"),
# #     ("POONTHURA", "POONTHURA"),
# #     ("PALLICHAL", "PALLICHAL"),
# #     ("MENAMKULAM", "MENAMKULAM"),
# #     ("ULIYAZHATHURA", "ULIYAZHATHURA"),
# #     ("ERAMALLOOR", "ERAMALLOOR"),
# #     ("MUVATTUPUZHA", "MUVATTUPUZHA"),
# #     ("VYPIN", "VYPIN"),
# #     ("ALUVA", "ALUVA"),
# #     ("THRISSUR", "THRISSUR"),
# #     ("PALAKKAD", "PALAKKAD"),
# #     ("KYASAPURA", "KYASAPURA"),
# #     ("NYOMA_1", "NYOMA_1"),
# #     ("TETHA", "TETHA"),
# #     ("KHULDO", "KHULDO"),
# #     ("NYOMA_2", "NYOMA_2"),
# #     ("CHUSHUL", "CHUSHUL"),
# #     ("MAN", "MAN"),
# #     ("ZULIDOK", "ZULIDOK"),
# #     ("SASPUL", "SASPUL"),
# #     ("TSATI", "TSATI"),
# #     ("TERCHEY", "TERCHEY"),
# #     ("TURTUK", "TURTUK"),
# #     ("CHANGLUNG", "CHANGLUNG"),
# #     ("KALPENI", "KALPENI"),
# #     ("KILTAN", "KILTAN"),
# #     ("BITRA", "BITRA"),
# #     ("CHETLAT", "CHETLAT"),
# #     ("KHAKNARKALAN", "KHAKNARKALAN"),
# #     ("ATHNER", "ATHNER"),
# #     ("GONAGHAT", "GONAGHAT"),
# #     ("SEGAON", "SEGAON"),
# #     ("BHIKANGAON", "BHIKANGAON"),
# #     ("CHIMANKHAPA", "CHIMANKHAPA"),
# #     ("DAHI", "DAHI"),
# #     ("PUNASA", "PUNASA"),
# #     ("AMARWARA", "AMARWARA"),
# #     ("KHIRSADI", "KHIRSADI"),
# #     ("BAGH", "BAGH"),
# #     ("SEONIMALWA", "SEONIMALWA"),
# #     ("KATTIWADAKHAS", "KATTIWADAKHAS"),
# #     ("ATARIYA ATARIYA", "ATARIYA ATARIYA"),
# #     ("INDORE_1", "INDORE_1"),
# #     ("INDORE_2", "INDORE_2"),
# #     ("INDORE_3", "INDORE_3"),
# #     ("GADARWARA", "GADARWARA"),
# #     ("DINDORI", "DINDORI"),
# #     ("KHEDA", "KHEDA"),
# #     ("JABALPUR_1", "JABALPUR_1"),
# #     ("BHOPAL_1", "BHOPAL_1"),
# #     ("UJJAIN_1", "UJJAIN_1"),
# #     ("UJJAIN_2", "UJJAIN_2"),
# #     ("JABALPUR_2", "JABALPUR_2"),
# #     ("BHOPAL_2", "BHOPAL_2"),
# #     ("BHOPAL_3", "BHOPAL_3"),
# #     ("SHAHDOL", "SHAHDOL"),
# #     ("KALAPIPAL", "KALAPIPAL"),
# #     ("PACHORE", "PACHORE"),
# #     ("DAMOH", "DAMOH"),
# #     ("SAGARNAGAR", "SAGARNAGAR"),
# #     ("SAGAR", "SAGAR"),
# #     ("PANTHPIPALIA", "PANTHPIPALIA"),
# #     ("TURKI_1", "TURKI_1"),
# #     ("MANGARAI", "MANGARAI"),
# #     ("MALTHON", "MALTHON"),
# #     ("PATNATAMOLI", "PATNATAMOLI"),
# #     ("SIDHI", "SIDHI"),
# #     ("DIGHWAR", "DIGHWAR"),
# #     ("ASHOKNAGAR", "ASHOKNAGAR"),
# #     ("SATNA", "SATNA"),
# #     ("MAUGANJ", "MAUGANJ"),
# #     ("SIRMAUR", "SIRMAUR"),
# #     ("TURKI_2", "TURKI_2"),
# #     ("NOWGAON", "NOWGAON"),
# #     ("MAGARDEH", "MAGARDEH"),
# #     ("BHITARWAR", "BHITARWAR"),
# #     ("KHOJIPURA", "KHOJIPURA"),
# #     ("SEONDHA", "SEONDHA"),
# #     ("GWALIOR_1", "GWALIOR_1"),
# #     ("GWALIOR_2", "GWALIOR_2"),
# #     ("MORENA", "MORENA"),
# #     ("DEVGAD", "DEVGAD"),
# #     ("SHIRALA", "SHIRALA"),
# #     ("RATNAGIRI", "RATNAGIRI"),
# #     ("MAYANI", "MAYANI"),
# #     ("SOLAPUR_1", "SOLAPUR_1"),
# #     ("SOLAPUR_2", "SOLAPUR_2"),
# #     ("SOLAPUR_3", "SOLAPUR_3"),
# #     ("PARANDA", "PARANDA"),
# #     ("MURUD", "MURUD"),
# #     ("KONDHWA", "KONDHWA"),
# #     ("KARVENAGAR", "KARVENAGAR"),
# #     ("PUNE_1", "PUNE_1"),
# #     ("PUNE_2", "PUNE_2"),
# #     ("PUNE_3", "PUNE_3"),
# #     ("PIMPRICHINCHWAD", "PIMPRICHINCHWAD"),
# #     ("SHELARWADI", "SHELARWADI"),
# #     ("AHMADPUR", "AHMADPUR"),
# #     ("KOPRA", "KOPRA"),
# #     ("APOLLOBANDARCOLABA", "APOLLOBANDARCOLABA"),
# #     ("NAVIMUMBAI", "NAVIMUMBAI"),
# #     ("PANVEL", "PANVEL"),
# #     ("MUMBAI_1", "MUMBAI_1"),
# #     ("TURBHE", "TURBHE"),
# #     ("TALOJA", "TALOJA"),
# #     ("MUMBAI_2", "MUMBAI_2"),
# #     ("MUMBAI_3", "MUMBAI_3"),
# #     ("MUMBAI_4", "MUMBAI_4"),
# #     ("THANE_1", "THANE_1"),
# #     ("MUMBAI_5", "MUMBAI_5"),
# #     ("DAMRANCHA", "DAMRANCHA"),
# #     ("THANE_2", "THANE_2"),
# #     ("PATHRI", "PATHRI"),
# #     ("THANE_3", "THANE_3"),
# #     ("KALYAN", "KALYAN"),
# #     ("NAIGAON", "NAIGAON"),
# #     ("NASHIK_1", "NASHIK_1"),
# #     ("KOLTHAN", "KOLTHAN"),
# #     ("NASHIK_2", "NASHIK_2"),
# #     ("JATWADA", "JATWADA"),
# #     ("NASHIK_3", "NASHIK_3"),
# #     ("ARNI", "ARNI"),
# #     ("MEHKAR", "MEHKAR"),
# #     ("SINDEWAHI", "SINDEWAHI"),
# #     ("NANDGAON", "NANDGAON"),
# #     ("YAVATMAL", "YAVATMAL"),
# #     ("GHATNANDRA", "GHATNANDRA"),
# #     ("HINGANGHAT", "HINGANGHAT"),
# #     ("DATTAPURDHAMANGAON", "DATTAPURDHAMANGAON"),
# #     ("MALKAPUR", "MALKAPUR"),
# #     ("AMRAVATI", "AMRAVATI"),
# #     ("NAGPUR_1", "NAGPUR_1"),
# #     ("KAMPTEE", "KAMPTEE"),
# #     ("NAGPUR_2", "NAGPUR_2"),
# #     ("AMGAONKH.", "AMGAONKH."),
# #     ("WARLA", "WARLA"),
# #     ("NARKHED", "NARKHED"),
# #     ("TOLBUNG", "TOLBUNG"),
# #     ("NAMBASHIKHULLEN", "NAMBASHIKHULLEN"),
# #     ("JATRAKONA-II", "JATRAKONA-II"),
# #     ("UMLŽ?REM", "UMLŽ?REM"),
# #     ("KHANAPARA", "KHANAPARA"),
# #     ("ZUNHEBOTO", "ZUNHEBOTO"),
# #     ("KADAGUDA", "KADAGUDA"),
# #     ("DIGAPAHANDI", "DIGAPAHANDI"),
# #     ("CHANDRAPUR", "CHANDRAPUR"),
# #     ("KHALIKOTE", "KHALIKOTE"),
# #     ("CHILIKANUAPADA", "CHILIKANUAPADA"),
# #     ("KOKSARA", "KOKSARA"),
# #     ("JUNAGARH", "JUNAGARH"),
# #     ("RAIGHAR", "RAIGHAR"),
# #     ("BHOGARA", "BHOGARA"),
# #     ("BOIRGAON", "BOIRGAON"),
# #     ("BHINGARPUR", "BHINGARPUR"),
# #     ("BHUASUNI", "BHUASUNI"),
# #     ("CUTTACK", "CUTTACK"),
# #     ("NARASINGHPUR", "NARASINGHPUR"),
# #     ("PURUNAKOT", "PURUNAKOT"),
# #     ("DEULDUNGURI", "DEULDUNGURI"),
# #     ("PATNAGARH", "PATNAGARH"),
# #     ("GARHAPARAJANG", "GARHAPARAJANG"),
# #     ("DANGAPAL", "DANGAPAL"),
# #     ("CHHENDIPADA", "CHHENDIPADA"),
# #     ("ANANDAPURPART", "ANANDAPURPART"),
# #     ("REAMAL", "REAMAL"),
# #     ("SAMBALPUR", "SAMBALPUR"),
# #     ("AHARAPADA", "AHARAPADA"),
# #     ("SARGIDIHI", "SARGIDIHI"),
# #     ("BADHUNIA", "BADHUNIA"),
# #     ("ROURKELA", "ROURKELA"),
# #     ("NETTAPAKKAM", "NETTAPAKKAM"),
# #     ("KUNICHAMPET", "KUNICHAMPET"),
# #     ("YANAM", "YANAM"),
# #     ("MOONAK", "MOONAK"),
# #     ("LEHRI", "LEHRI"),
# #     ("MALOUT", "MALOUT"),
# #     ("CHAURA", "CHAURA"),
# #     ("FAZILKA", "FAZILKA"),
# #     ("MALERKOTLA", "MALERKOTLA"),
# #     ("KOTKAPURA", "KOTKAPURA"),
# #     ("SASNAGAR(MOHALI)_1", "SASNAGAR(MOHALI)_1"),
# #     ("SASNAGAR(MOHALI)_2", "SASNAGAR(MOHALI)_2"),
# #     ("FOCALPOINT", "FOCALPOINT"),
# #     ("INDUSTRIALZONE", "INDUSTRIALZONE"),
# #     ("FIROZPUR", "FIROZPUR"),
# #     ("GARHSHANKAR", "GARHSHANKAR"),
# #     ("CHHOTIBARANDARII", "CHHOTIBARANDARII"),
# #     ("HUSSAINPUR", "HUSSAINPUR"),
# #     ("BASTIBAWAKHEL", "BASTIBAWAKHEL"),
# #     ("SULTANWIND", "SULTANWIND"),
# #     ("CHHEHARTA", "CHHEHARTA"),
# #     ("AJNALA", "AJNALA"),
# #     ("DERABABANANAK", "DERABABANANAK"),
# #     ("MARARA", "MARARA"),
# #     ("SAJJANGARH", "SAJJANGARH"),
# #     ("KOTRI", "KOTRI"),
# #     ("RISHABHDEO", "RISHABHDEO"),
# #     ("DHARIAWAD", "DHARIAWAD"),
# #     ("PIRAWA", "PIRAWA"),
# #     ("PHALASIYA", "PHALASIYA"),
# #     ("SARDA DUNGAR GARH", "SARDA DUNGAR GARH"),
# #     ("ABUROAD", "ABUROAD"),
# #     ("ASNAWAR", "ASNAWAR"),
# #     ("SUKHER", "SUKHER"),
# #     ("KANERA", "KANERA"),
# #     ("JALBERI", "JALBERI"),
# #     ("BARAN", "BARAN"),
# #     ("SHRINATHPURAM", "SHRINATHPURAM"),
# #     ("KANSUWA", "KANSUWA"),
# #     ("SUMERPUR", "SUMERPUR"),
# #     ("GUDHAMALANI", "GUDHAMALANI"),
# #     ("BAGODA", "BAGODA"),
# #     ("GANGAPUR", "GANGAPUR"),
# #     ("RAILWAYSTATIONAREA", "RAILWAYSTATIONAREA"),
# #     ("MANDALGARH", "MANDALGARH"),
# #     ("SHAHPURA_1", "SHAHPURA_1"),
# #     ("SIWANA", "SIWANA"),
# #     ("RAMA", "RAMA"),
# #     ("DEI", "DEI"),
# #     ("MARWARJUNCTION", "MARWARJUNCTION"),
# #     ("ASIND", "ASIND"),
# #     ("GADRAROAD", "GADRAROAD"),
# #     ("BARMER", "BARMER"),
# #     ("PANCHLA", "PANCHLA"),
# #     ("KHANDAR", "KHANDAR"),
# #     ("KALYANPUR", "KALYANPUR"),
# #     ("MANPURAKHARDA", "MANPURAKHARDA"),
# #     ("JOGIDASKAGAON", "JOGIDASKAGAON"),
# #     ("MALPURA", "MALPURA"),
# #     ("BONLI", "BONLI"),
# #     ("SINDHIPURA", "SINDHIPURA"),
# #     ("BEENJOTA", "BEENJOTA"),
# #     ("HATHIKHERA", "HATHIKHERA"),
# #     ("SARMATHURA", "SARMATHURA"),
# #     ("GHOOGHRA", "GHOOGHRA"),
# #     ("LOONAR", "LOONAR"),
# #     ("PHAGI", "PHAGI"),
# #     ("NADOTI", "NADOTI"),
# #     ("DECHOO", "DECHOO"),
# #     ("JEEROTA", "JEEROTA"),
# #     ("ROOPANGARH", "ROOPANGARH"),
# #     ("KANOI", "KANOI"),
# #     ("KISHANPURAATLALWAS", "KISHANPURAATLALWAS"),
# #     ("KUCHERA", "KUCHERA"),
# #     ("SHAHGARH", "SHAHGARH"),
# #     ("BHARATPUR", "BHARATPUR"),
# #     ("GUWARA SOTI", "GUWARA SOTI"),
# #     ("AAU", "AAU"),
# #     ("NADBAI", "NADBAI"),
# #     ("JAYAL", "JAYAL"),
# #     ("RAJGARH", "RAJGARH"),
# #     ("DANTARAMGARH", "DANTARAMGARH"),
# #     ("NAGAUR", "NAGAUR"),
# #     ("SHAHPURA_2", "SHAHPURA_2"),
# #     ("DIDWANA", "DIDWANA"),
# #     ("SHRIMADHOPUR", "SHRIMADHOPUR"),
# #     ("LONGEWALA", "LONGEWALA"),
# #     ("SUTHAR MANDI", "SUTHAR MANDI"),
# #     ("NOKHA", "NOKHA"),
# #     ("KAMAN", "KAMAN"),
# #     ("NECHHWA", "NECHHWA"),
# #     ("NAWALGARH", "NAWALGARH"),
# #     ("MUNDAWAR", "MUNDAWAR"),
# #     ("KISHANGARH", "KISHANGARH"),
# #     ("RANJITPURA", "RANJITPURA"),
# #     ("BIWANDI", "BIWANDI"),
# #     ("ROOPNAGAR", "ROOPNAGAR"),
# #     ("SURAJGARH", "SURAJGARH"),
# #     ("SOMASAR", "SOMASAR"),
# #     ("LUNKARANSAR", "LUNKARANSAR"),
# #     ("RANISAR", "RANISAR"),
# #     ("RAWLAMANDI", "RAWLAMANDI"),
# #     ("NOHAR", "NOHAR"),
# #     ("ANUPGARH", "ANUPGARH"),
# #     ("SURATGARH", "SURATGARH"),
# #     ("UMEWALA", "UMEWALA"),
# #     ("SRIGANGANAGAR", "SRIGANGANAGAR"),
# #     ("NAMCHI", "NAMCHI"),
# #     ("RESHI", "RESHI"),
# #     ("DENTAM", "DENTAM"),
# #     ("YANGYANG", "YANGYANG"),
# #     ("KUPUP", "KUPUP"),
# #     ("LACHEN", "LACHEN"),
# #     ("THANGU VALLEY", "THANGU VALLEY"),
# #     ("THOOTHUKUDI_1", "THOOTHUKUDI_1"),
# #     ("THOOTHUKUDI_2", "THOOTHUKUDI_2"),
# #     ("THIRUPARANKUNDRAM", "THIRUPARANKUNDRAM"),
# #     ("MADURAI_1", "MADURAI_1"),
# #     ("MADURAI_2", "MADURAI_2"),
# #     ("MADURAI_3", "MADURAI_3"),
# #     ("DINDIGUL_1", "DINDIGUL_1"),
# #     ("DINDIGUL_2", "DINDIGUL_2"),
# #     ("DINDIGUL_3", "DINDIGUL_3"),
# #     ("TIRUCHIRAPPALLI_1", "TIRUCHIRAPPALLI_1"),
# #     ("THANJAVUR_1", "THANJAVUR_1"),
# #     ("THANJAVUR_2", "THANJAVUR_2"),
# #     ("THANJAVUR_3", "THANJAVUR_3"),
# #     ("THIRUVERUMBUR", "THIRUVERUMBUR"),
# #     ("TIRUCHIRAPPALLI_2", "TIRUCHIRAPPALLI_2"),
# #     ("PODANUR", "PODANUR"),
# #     ("COIMBATORE_1", "COIMBATORE_1"),
# #     ("COIMBATORE_2", "COIMBATORE_2"),
# #     ("ARULPURAM", "ARULPURAM"),
# #     ("COIMBATORE_3", "COIMBATORE_3"),
# #     ("TIRUPPUR_1", "TIRUPPUR_1"),
# #     ("TIRUPPUR_2", "TIRUPPUR_2"),
# #     ("TIRUPPUR_3", "TIRUPPUR_3"),
# #     ("ERODE_1", "ERODE_1"),
# #     ("ERODE_2", "ERODE_2"),
# #     ("PALLIPALAYAM", "PALLIPALAYAM"),
# #     ("SALEM_1", "SALEM_1"),
# #     ("SALEM_2", "SALEM_2"),
# #     ("SALEM_3", "SALEM_3"),
# #     ("VELLORE_1", "VELLORE_1"),
# #     ("VELLORE_2", "VELLORE_2"),
# #     ("KARAPAKKAM", "KARAPAKKAM"),
# #     ("VELLORE_3", "VELLORE_3"),
# #     ("TAMBARAM", "TAMBARAM"),
# #     ("VELLORE_4", "VELLORE_4"),
# #     ("ANNANUR", "ANNANUR"),
# #     ("VALLUR", "VALLUR"),
# #     ("AIZA", "AIZA"),
# #     ("YERRUPALEM", "YERRUPALEM"),
# #     ("GARIDEPALLI", "GARIDEPALLI"),
# #     ("KURMALGUDA", "KURMALGUDA"),
# #     ("RAJENDRANAGARMANDAL", "RAJENDRANAGARMANDAL"),
# #     ("HAYATNAGAR_1", "HAYATNAGAR_1"),
# #     ("MARIPEDA", "MARIPEDA"),
# #     ("GUMMADIVALLI", "GUMMADIVALLI"),
# #     ("HYDERABAD_1", "HYDERABAD_1"),
# #     ("SECUNDERABAD_1", "SECUNDERABAD_1"),
# #     ("HYDERABAD_2", "HYDERABAD_2"),
# #     ("KAREPALLI", "KAREPALLI"),
# #     ("SECUNDERABAD_2", "SECUNDERABAD_2"),
# #     ("ZAHIRABAD", "ZAHIRABAD"),
# #     ("KOTHAGUDA", "KOTHAGUDA"),
# #     ("KHAZIPET", "KHAZIPET"),
# #     ("WARANGAL", "WARANGAL"),
# #     ("HANUMAKONDA_1", "HANUMAKONDA_1"),
# #     ("HANUMAKONDA_2", "HANUMAKONDA_2"),
# #     ("KANGTI", "KANGTI"),
# #     ("KARIMNAGAR_1", "KARIMNAGAR_1"),
# #     ("KARIMNAGAR_2", "KARIMNAGAR_2"),
# #     ("MANTHANI", "MANTHANI"),
# #     ("KAMMARPALLI", "KAMMARPALLI"),
# #     ("DANDEPALLI", "DANDEPALLI"),
# #     ("LINGAPUR", "LINGAPUR"),
# #     ("SIRIKONDA", "SIRIKONDA"),
# #     ("KAILASHAHAR", "KAILASHAHAR"),
# #     ("RAJAPUR", "RAJAPUR"),
# #     ("VARANASI_1", "VARANASI_1"),
# #     ("MUGHALSARAI", "MUGHALSARAI"),
# #     ("VARANASI_2", "VARANASI_2"),
# #     ("SADWAKALAN", "SADWAKALAN"),
# #     ("VARANASI_3", "VARANASI_3"),
# #     ("CHEDIBEER", "CHEDIBEER"),
# #     ("PRAYAGRAJ", "PRAYAGRAJ"),
# #     ("NAGRA", "NAGRA"),
# #     ("KABIRNAGAR", "KABIRNAGAR"),
# #     ("JHANSI", "JHANSI"),
# #     ("OLDKATRA", "OLDKATRA"),
# #     ("BABERU", "BABERU"),
# #     ("GARSARI", "GARSARI"),
# #     ("MEHNAGAR", "MEHNAGAR"),
# #     ("MANIRAMPUR", "MANIRAMPUR"),
# #     ("PATTI", "PATTI"),
# #     ("JAMINKAKARGHATTI", "JAMINKAKARGHATTI"),
# #     ("SHAHGANJ", "SHAHGANJ"),
# #     ("ATRAULIA", "ATRAULIA"),
# #     ("MANPUR", "MANPUR"),
# #     ("RAMPURA", "RAMPURA"),
# #     ("NAUBASTA", "NAUBASTA"),
# #     ("JAJMAU", "JAJMAU"),
# #     ("PANKI", "PANKI"),
# #     ("CIVILLINES", "CIVILLINES"),
# #     ("UTELA", "UTELA"),
# #     ("NAWABGANJ", "NAWABGANJ"),
# #     ("BARAULIKHALILABAD", "BARAULIKHALILABAD"),
# #     ("KHALILABAD", "KHALILABAD"),
# #     ("BAIRIALIPUR", "BAIRIALIPUR"),
# #     ("LUCKNOW", "LUCKNOW"),
# #     ("DAULATGANJ", "DAULATGANJ"),
# #     ("BARABANKI", "BARABANKI"),
# #     ("MUDIYAR", "MUDIYAR"),
# #     ("MOYAIYANPUR", "MOYAIYANPUR"),
# #     ("DOMARIYAGANJ", "DOMARIYAGANJ"),
# #     ("SURUCHIPURAMCOLONY", "SURUCHIPURAMCOLONY"),
# #     ("AGRA", "AGRA"),
# #     ("MAHMUDABAD", "MAHMUDABAD"),
# #     ("AKBARPURAUNCHHA", "AKBARPURAUNCHHA"),
# #     ("NAUTANWA", "NAUTANWA"),
# #     ("GOPALPUR", "GOPALPUR"),
# #     ("PACHPERWA", "PACHPERWA"),
# #     ("GOPAMAU", "GOPAMAU"),
# #     ("BAMHNAWA", "BAMHNAWA"),
# #     ("SIKANDRARAO", "SIKANDRARAO"),
# #     ("BHINGA", "BHINGA"),
# #     ("DHANIPUR", "DHANIPUR"),
# #     ("DHAURRAMAFI", "DHAURRAMAFI"),
# #     ("RANJITGARHI", "RANJITGARHI"),
# #     ("BUDAUN", "BUDAUN"),
# #     ("NIGOHI", "NIGOHI"),
# #     ("HARKHAPUR", "HARKHAPUR"),
# #     ("KHURJA", "KHURJA"),
# #     ("AONLA", "AONLA"),
# #     ("BHIRA", "BHIRA"),
# #     ("PATELBIHARCOLONY", "PATELBIHARCOLONY"),
# #     ("GREATERNOIDA", "GREATERNOIDA"),
# #     ("CHANDANCHAUKI", "CHANDANCHAUKI"),
# #     ("NOIDA", "NOIDA"),
# #     ("PILIBHIT", "PILIBHIT"),
# #     ("GHAZIABAD", "GHAZIABAD"),
# #     ("HASANPUR", "HASANPUR"),
# #     ("TASHKA", "TASHKA"),
# #     ("HAYATNAGAR_2", "HAYATNAGAR_2"),
# #     ("LALIYANA", "LALIYANA"),
# #     ("BAGPAT", "BAGPAT"),
# #     ("BIJNOR", "BIJNOR"),
# #     ("SHAMLI", "SHAMLI"),
# #     ("SAHARANPUR_1", "SAHARANPUR_1"),
# #     ("SAHARANPUR_2", "SAHARANPUR_2"),
# #     ("SAHARANPUR_3", "SAHARANPUR_3"),
# #     ("JHALAKUDI", "JHALAKUDI"),
# #     ("BHINGRADRANGE", "BHINGRADRANGE"),
# #     ("KALAGARH", "KALAGARH"),
# #     ("NAINIDANDA", "NAINIDANDA"),
# #     ("DHARCHULA", "DHARCHULA"),
# #     ("TEEJAM", "TEEJAM"),
# #     ("BHARARISAIN", "BHARARISAIN"),
# #     ("KALAPANI", "KALAPANI"),
# #     ("DEHRADUN_1", "DEHRADUN_1"),
# #     ("DEHRADUN_2", "DEHRADUN_2"),
# #     ("KUTI", "KUTI"),
# #     ("DEHRADUN_3", "DEHRADUN_3"),
# #     ("DEHRADUN_4", "DEHRADUN_4"),
# #     ("KEDARNATH", "KEDARNATH"),
# #     ("BADRINATH", "BADRINATH"),
# #     ("GANGOTRI", "GANGOTRI"),
# #     ("BAKKHALI", "BAKKHALI"),
# #     ("BALIGERIA", "BALIGERIA"),
# #     ("HALDIA", "HALDIA"),
# #     ("RAJPURSONARPUR", "RAJPURSONARPUR"),
# #     ("PURBAPUTIARY", "PURBAPUTIARY"),
# #     ("PUJALI", "PUJALI"),
# #     ("MAHESHTALA", "MAHESHTALA"),
# #     ("KGHODHATI", "KGHODHATI"),
# #     ("KOLKATA", "KOLKATA"),
# #     ("RAJARHAT", "RAJARHAT"),
# #     ("HOWRAH_1", "HOWRAH_1"),
# #     ("HOWRAH_2", "HOWRAH_2"),
# #     ("MADHYAMGRAM", "MADHYAMGRAM"),
# #     ("RAJYADHARPUR", "RAJYADHARPUR"),
# #     ("BAGHMUNDI", "BAGHMUNDI"),
# #     ("MAJHDIA", "MAJHDIA"),
# #     ("BAMUNARA", "BAMUNARA"),
# #     ("DURGAPUR_1", "DURGAPUR_1"),
# #     ("DURGAPUR_2", "DURGAPUR_2"),
# #     ("BETAI", "BETAI"),
# #     ("KHARIBONA", "KHARIBONA"),
# #     ("RAGHUNATHGANJ", "RAGHUNATHGANJ"),
# #     ("KALIACHAK", "KALIACHAK"),
# #     ("BARTALI", "BARTALI"),
# #     ("KUMARGANJ", "KUMARGANJ"),
# #     ("KALIYAGANJ", "KALIYAGANJ"),
# #     ("ISLAMPUR", "ISLAMPUR"),
# #     ("HALDIBARI", "HALDIBARI"),
# #     ("KUMARGRAM", "KUMARGRAM"),
# #     ("JAIGAON", "JAIGAON"),
# #     ("SUKHANIBASTI", "SUKHANIBASTI"),
# # ]
# # print(len(STATION_CHOICES))

# # # STATUS_CHOICES = [
# # #     ("DRAFT", "Draft"),
# # #     ("SUBMITTED", "Submitted"),
# # #     ("SUPERVISOR_APPROVED", "Supervisor Approved"),
# # #     ("DIRECTOR_APPROVED", "Director Approved"),
# # #     ("ZONAL_CHIEF_APPROVED", "Zonal Chief Approved"),
# # #     ("GNRB_APPROVED", "GNRB Approved"),
# # #     ("REJECTED", "Rejected"),
# # # ]


# # # class YourModel(models.Model):
# # #     STATUS_CHOICES = STATUS_CHOICES
# # #     STATION_CHOICES = STATION_CHOICES

# # #     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
# # #     station = models.CharField(max_length=150, choices=STATION_CHOICES)
# # #     surveyor = models.ForeignKey(User, on_delete=models.CASCADE)
# # #     status = models.CharField(max_length=30, choices=STATUS_CHOICES, default="DRAFT")
# # #     remarks = models.TextField(blank=True, null=True)
# # #     created_at = models.DateTimeField(auto_now_add=True)
# # #     updated_at = models.DateTimeField(auto_now=True)

# # #     def __str__(self):
# # #         return f"{self.station} - {self.status}"

# # #     class Meta:
# # #         ordering = ['-created_at']

# STATION_CHOICES = [
#     ("CHITTOOR", "CHITTOOR"),
#     ("THATITHAPU", "THATITHAPU"),
#     ("PELLAKUR", "PELLAKUR"),
#     ("TSUNDUPALLE", "TSUNDUPALLE"),
#     ("CHILLAKUR", "CHILLAKUR"),
#     ("GUMMAGATTA", "GUMMAGATTA"),
#     ("KALUVOYA", "KALUVOYA"),
#     ("ATLUR", "ATLUR"),
#     ("GARLADINNE", "GARLADINNE"),
#     ("KODUR", "KODUR"),
#     ("VIDAPANAKAL", "VIDAPANAKAL"),
#     ("VALETIVARIPALEM", "VALETIVARIPALEM"),
#     ("RUDRAVARAM", "RUDRAVARAM"),
#     ("PATTIKONDA", "PATTIKONDA"),
#     ("ADONI", "ADONI"),
#     ("VELDHURTHY", "VELDHURTHY"),
#     ("MANGALAGIRI", "MANGALAGIRI"),
#     ("SANATHNAGAR", "SANATHNAGAR"),
#     ("THULLUR", "THULLUR"),
#     ("KROSUR", "KROSUR"),
#     ("GOLLAPUDI", "GOLLAPUDI"),
#     ("KOYYALAGUDEM", "KOYYALAGUDEM"),
#     ("PETTUGOLLAPALLE", "PETTUGOLLAPALLE"),
#     ("ADDATEEGALA", "ADDATEEGALA"),
#     ("MAREDUMILLI", "MAREDUMILLI"),
#     ("GANGAVARAM", "GANGAVARAM"),
#     ("MVPCOLONY", "MVPCOLONY"),
#     ("VISHAKHAPATTANAM", "VISHAKHAPATTANAM"),
#     ("CHINTAPALLI", "CHINTAPALLI"),
#     ("SRIKAKULAM", "SRIKAKULAM"),
#     ("PARVATIPURAM", "PARVATIPURAM"),
#     ("PANGCHAO", "PANGCHAO"),
#     ("VIJOYNAGAR", "VIJOYNAGAR"),
#     ("NAMPONG", "NAMPONG"),
#     ("LADAHQ", "LADAHQ"),
#     ("CHAYANGTAJO", "CHAYANGTAJO"),
#     ("PASIGHAT", "PASIGHAT"),
#     ("LONGDING KOLING HQ", "LONGDING KOLING HQ"),
#     ("CHAGLAGAM", "CHAGLAGAM"),
#     ("LIMEKINGH.Q", "LIMEKINGH.Q"),
#     ("KARGONG", "KARGONG"),
#     ("PIDI", "PIDI"),
#     ("ANINI", "ANINI"),
#     ("SINGA", "SINGA"),
#     ("KARIMGANJ", "KARIMGANJ"),
#     ("JALUKBARI", "JALUKBARI"),
#     ("GOALPARA", "GOALPARA"),
#     ("PANIKHAITI", "PANIKHAITI"),
#     ("KHANABARIANIANI", "KHANABARIANIANI"),
#     ("BARGAON", "BARGAON"),
#     ("BARKHOPA", "BARKHOPA"),
#     ("UDHIYAGURI", "UDHIYAGURI"),
#     ("BISWANATHCIRCLE", "BISWANATHCIRCLE"),
#     ("JORHAT", "JORHAT"),
#     ("DEMOW", "DEMOW"),
#     ("TETARIYAKHURD", "TETARIYAKHURD"),
#     ("CHAKAI", "CHAKAI"),
#     ("RAFIGANJ", "RAFIGANJ"),
#     ("BHAGALPUR", "BHAGALPUR"),
#     ("AHMADABAD", "AHMADABAD"),
#     ("RAWAICH", "RAWAICH"),
#     ("AZAMNAGAR", "AZAMNAGAR"),
#     ("MARUUFGANJ", "MARUUFGANJ"),
#     ("ROUN", "ROUN"),
#     ("DIGHA", "DIGHA"),
#     ("MANORI", "MANORI"),
#     ("KUKRAUN", "KUKRAUN"),
#     ("CHHITWARAKAPUR", "CHHITWARAKAPUR"),
#     ("BAISI", "BAISI"),
#     ("LAHERIASARAI", "LAHERIASARAI"),
#     ("KURSAKATTA", "KURSAKATTA"),
#     ("ASHOGI", "ASHOGI"),
#     ("PURBIKARGAHIA", "PURBIKARGAHIA"),
#     ("SONBARSA", "SONBARSA"),
#     ("NAURANGIA", "NAURANGIA"),
#     ("MADHYAMARG", "MADHYAMARG"),
#     ("KIRANDUL", "KIRANDUL"),
#     ("METAPAL", "METAPAL"),
#     ("UTLA", "UTLA"),
#     ("BENIDHARAUR", "BENIDHARAUR"),
#     ("ROTAD", "ROTAD"),
#     ("VISHRAMPURI", "VISHRAMPURI"),
#     ("ANTAGARH", "ANTAGARH"),
#     ("BHANUPRATAPPUR", "BHANUPRATAPPUR"),
#     ("NAGRI", "NAGRI"),
#     ("KHADGAON", "KHADGAON"),
#     ("PIPARCHHEDI", "PIPARCHHEDI"),
#     ("ATALNAGAR-NAVA", "ATALNAGAR-NAVA"),
#     ("PITHORA", "PITHORA"),
#     ("BIRGOAN", "BIRGOAN"),
#     ("KHAIRAHA", "KHAIRAHA"),
#     ("GUNARBAD", "GUNARBAD"),
#     ("DABHARA", "DABHARA"),
#     ("KHADI", "KHADI"),
#     ("NAWAGARH", "NAWAGARH"),
#     ("BALODA", "BALODA"),
#     ("PALI", "PALI"),
#     ("SHAHPUR", "SHAHPUR"),
#     ("KORBI", "KORBI"),
#     ("JHIRMITI", "JHIRMITI"),
#     ("KELHARI", "KELHARI"),
#     ("SINDHOR", "SINDHOR"),
#     ("RAMANUJGANJ", "RAMANUJGANJ"),
#     ("FUDAM", "FUDAM"),
#     ("DELHI_1", "DELHI_1"),
#     ("DELHI_2", "DELHI_2"),
#     ("DELHI_3", "DELHI_3"),
#     ("DELHI_4", "DELHI_4"),
#     ("VASCODAGAMA", "VASCODAGAMA"),
#     ("OLDGOA", "OLDGOA"),
#     ("CALANGUTE", "CALANGUTE"),
#     ("VERAVAL", "VERAVAL"),
#     ("RAJULA", "RAJULA"),
#     ("JUNAGADH", "JUNAGADH"),
#     ("JESHAR", "JESHAR"),
#     ("JASDAN", "JASDAN"),
#     ("KAVANT", "KAVANT"),
#     ("BERAJA", "BERAJA"),
#     ("DWARKA", "DWARKA"),
#     ("RAJKOT_1", "RAJKOT_1"),
#     ("RAJKOT_2", "RAJKOT_2"),
#     ("KHAMBHAT", "KHAMBHAT"),
#     ("JODIYA", "JODIYA"),
#     ("VEKARIYA", "VEKARIYA"),
#     ("MUNDRA", "MUNDRA"),
#     ("MALIA", "MALIA"),
#     ("NAKHATRANA", "NAKHATRANA"),
#     ("MEGHRAJ", "MEGHRAJ"),
#     ("SAMI", "SAMI"),
#     ("SANTALPUR", "SANTALPUR"),
#     ("SATLASANA", "SATLASANA"),
#     ("BHABHAR", "BHABHAR"),
#     ("DHANERA", "DHANERA"),
#     ("MAVSARI", "MAVSARI"),
#     ("FARIDABAD", "FARIDABAD"),
#     ("GURUGRAM_1", "GURUGRAM_1"),
#     ("GURUGRAM_2", "GURUGRAM_2"),
#     ("CHARKHIDADRI", "CHARKHIDADRI"),
#     ("ISHARWAL", "ISHARWAL"),
#     ("MADINA", "MADINA"),
#     ("BHATTUMANDI", "BHATTUMANDI"),
#     ("NARWANA", "NARWANA"),
#     ("KARNAL_1", "KARNAL_1"),
#     ("KARNAL_2", "KARNAL_2"),
#     ("PEHOWA", "PEHOWA"),
#     ("PANCHKULA", "PANCHKULA"),
#     ("SHIMLA_1", "SHIMLA_1"),
#     ("SHIMLA_2", "SHIMLA_2"),
#     ("SHIMLA_3", "SHIMLA_3"),
#     ("SOONA", "SOONA"),
#     ("RECKONGPEO", "RECKONGPEO"),
#     ("PUNASPA", "PUNASPA"),
#     ("HAMIRPUR", "HAMIRPUR"),
#     ("BANJAR", "BANJAR"),
#     ("UPMOHALDANMOCHHE", "UPMOHALDANMOCHHE"),
#     ("NAKO", "NAKO"),
#     ("BARSHAINI", "BARSHAINI"),
#     ("TABO", "TABO"),
#     ("KAZA", "KAZA"),
#     ("DAMPHUG", "DAMPHUG"),
#     ("HANSA", "HANSA"),
#     ("CHOBIA", "CHOBIA"),
#     ("KEYLONG", "KEYLONG"),
#     ("KUKUMSERI", "KUKUMSERI"),
#     ("PARGHWAL", "PARGHWAL"),
#     ("SUCHETGARH", "SUCHETGARH"),
#     ("JAMMU", "JAMMU"),
#     ("GULABGARH", "GULABGARH"),
#     ("RAJOURI", "RAJOURI"),
#     ("URI", "URI"),
#     ("SRINAGAR", "SRINAGAR"),
#     ("SISAI", "SISAI"),
#     ("DUMRI", "DUMRI"),
#     ("RANCHI_1", "RANCHI_1"),
#     ("RANCHI_2", "RANCHI_2"),
#     ("BISHUNPUR", "BISHUNPUR"),
#     ("RANCHI_3", "RANCHI_3"),
#     ("RANCHI_4", "RANCHI_4"),
#     ("KHALARI", "KHALARI"),
#     ("MAJHAULI", "MAJHAULI"),
#     ("PAKURIA", "PAKURIA"),
#     ("SATGAWAN", "SATGAWAN"),
#     ("GUNDLUPETE", "GUNDLUPETE"),
#     ("RAMAPURA", "RAMAPURA"),
#     ("MAHADESHWARABETTA", "MAHADESHWARABETTA"),
#     ("MYSURU_1", "MYSURU_1"),
#     ("MYSURU_2", "MYSURU_2"),
#     ("RAJAPURA", "RAJAPURA"),
#     ("HEBBAL", "HEBBAL"),
#     ("ARAKALAGUD", "ARAKALAGUD"),
#     ("KONAPPANAAGRAHARA", "KONAPPANAAGRAHARA"),
#     ("BENGALURU_1", "BENGALURU_1"),
#     ("MANGALURU_1", "MANGALURU_1"),
#     ("MANGALURU_2", "MANGALURU_2"),
#     ("MANGALURU_3", "MANGALURU_3"),
#     ("BENGALURU_2", "BENGALURU_2"),
#     ("MANGALURU_4", "MANGALURU_4"),
#     ("BENGALURU_3", "BENGALURU_3"),
#     ("BENGALURU_4", "BENGALURU_4"),
#     ("BEDISWASTE", "BEDISWASTE"),
#     ("GADENAHALLI", "GADENAHALLI"),
#     ("KALASA", "KALASA"),
#     ("TUMAKURU_1", "TUMAKURU_1"),
#     ("TUMAKURU_2", "TUMAKURU_2"),
#     ("TUMAKURU_3", "TUMAKURU_3"),
#     ("CHINTAMANI", "CHINTAMANI"),
#     ("NARASIMHARAJAPURA", "NARASIMHARAJAPURA"),
#     ("SIRA", "SIRA"),
#     ("HOSADURGA", "HOSADURGA"),
#     ("SHIVAMOGGA_1", "SHIVAMOGGA_1"),
#     ("SHIVAMOGGA_2", "SHIVAMOGGA_2"),
#     ("SHIVAMOGGA_3", "SHIVAMOGGA_3"),
#     ("SAGARA", "SAGARA"),
#     ("DAVANAGERE", "DAVANAGERE"),
#     ("HAVERI", "HAVERI"),
#     ("MUNDGOD", "MUNDGOD"),
#     ("HUVINAHADAGALI", "HUVINAHADAGALI"),
#     ("JOIDA", "JOIDA"),
#     ("HUBBALLI_1", "HUBBALLI_1"),
#     ("KURUGODU", "KURUGODU"),
#     ("HUBBALLI_2", "HUBBALLI_2"),
#     ("HUBBALLI_3", "HUBBALLI_3"),
#     ("KANAKAGIRI", "KANAKAGIRI"),
#     ("BELAGAVI_1", "BELAGAVI_1"),
#     ("BELAGAVI_2", "BELAGAVI_2"),
#     ("BELAGAVI_3", "BELAGAVI_3"),
#     ("MANVI", "MANVI"),
#     ("BAGALKOT", "BAGALKOT"),
#     ("CHIKODI", "CHIKODI"),
#     ("BASAVANABAGEWADI", "BASAVANABAGEWADI"),
#     ("SHAHAPUR", "SHAHAPUR"),
#     ("ALMEL", "ALMEL"),
#     ("CHINCHOLI", "CHINCHOLI"),
#     ("ALAND", "ALAND"),
#     ("POONTHURA", "POONTHURA"),
#     ("PALLICHAL", "PALLICHAL"),
#     ("MENAMKULAM", "MENAMKULAM"),
#     ("ULIYAZHATHURA", "ULIYAZHATHURA"),
#     ("ERAMALLOOR", "ERAMALLOOR"),
#     ("MUVATTUPUZHA", "MUVATTUPUZHA"),
#     ("VYPIN", "VYPIN"),
#     ("ALUVA", "ALUVA"),
#     ("THRISSUR", "THRISSUR"),
#     ("PALAKKAD", "PALAKKAD"),
#     ("KYASAPURA", "KYASAPURA"),
#     ("NYOMA_1", "NYOMA_1"),
#     ("TETHA", "TETHA"),
#     ("KHULDO", "KHULDO"),
#     ("NYOMA_2", "NYOMA_2"),
#     ("CHUSHUL", "CHUSHUL"),
#     ("MAN", "MAN"),
#     ("ZULIDOK", "ZULIDOK"),
#     ("SASPUL", "SASPUL"),
#     ("TSATI", "TSATI"),
#     ("TERCHEY", "TERCHEY"),
#     ("TURTUK", "TURTUK"),
#     ("CHANGLUNG", "CHANGLUNG"),
#     ("KALPENI", "KALPENI"),
#     ("KILTAN", "KILTAN"),
#     ("BITRA", "BITRA"),
#     ("CHETLAT", "CHETLAT"),
#     ("KHAKNARKALAN", "KHAKNARKALAN"),
#     ("ATHNER", "ATHNER"),
#     ("GONAGHAT", "GONAGHAT"),
#     ("SEGAON", "SEGAON"),
#     ("BHIKANGAON", "BHIKANGAON"),
#     ("CHIMANKHAPA", "CHIMANKHAPA"),
#     ("DAHI", "DAHI"),
#     ("PUNASA", "PUNASA"),
#     ("AMARWARA", "AMARWARA"),
#     ("KHIRSADI", "KHIRSADI"),
#     ("BAGH", "BAGH"),
#     ("SEONIMALWA", "SEONIMALWA"),
#     ("KATTIWADAKHAS", "KATTIWADAKHAS"),
#     ("ATARIYA_x000D_ATARIYA", "ATARIYA_x000D_ATARIYA"),
#     ("INDORE_1", "INDORE_1"),
#     ("INDORE_2", "INDORE_2"),
#     ("INDORE_3", "INDORE_3"),
#     ("GADARWARA", "GADARWARA"),
#     ("DINDORI", "DINDORI"),
#     ("KHEDA", "KHEDA"),
#     ("JABALPUR_1", "JABALPUR_1"),
#     ("BHOPAL_1", "BHOPAL_1"),
#     ("UJJAIN_1", "UJJAIN_1"),
#     ("UJJAIN_2", "UJJAIN_2"),
#     ("JABALPUR_2", "JABALPUR_2"),
#     ("BHOPAL_2", "BHOPAL_2"),
#     ("BHOPAL_3", "BHOPAL_3"),
#     ("SHAHDOL", "SHAHDOL"),
#     ("KALAPIPAL", "KALAPIPAL"),
#     ("PACHORE", "PACHORE"),
#     ("DAMOH", "DAMOH"),
#     ("SAGARNAGAR", "SAGARNAGAR"),
#     ("SAGAR", "SAGAR"),
#     ("PANTHPIPALIA", "PANTHPIPALIA"),
#     ("TURKI_1", "TURKI_1"),
#     ("MANGARAI", "MANGARAI"),
#     ("MALTHON", "MALTHON"),
#     ("PATNATAMOLI", "PATNATAMOLI"),
#     ("SIDHI", "SIDHI"),
#     ("DIGHWAR", "DIGHWAR"),
#     ("ASHOKNAGAR", "ASHOKNAGAR"),
#     ("SATNA", "SATNA"),
#     ("MAUGANJ", "MAUGANJ"),
#     ("SIRMAUR", "SIRMAUR"),
#     ("TURKI_2", "TURKI_2"),
#     ("NOWGAON", "NOWGAON"),
#     ("MAGARDEH", "MAGARDEH"),
#     ("BHITARWAR", "BHITARWAR"),
#     ("KHOJIPURA", "KHOJIPURA"),
#     ("SEONDHA", "SEONDHA"),
#     ("GWALIOR_1", "GWALIOR_1"),
#     ("GWALIOR_2", "GWALIOR_2"),
#     ("MORENA", "MORENA"),
#     ("DEVGAD", "DEVGAD"),
#     ("SHIRALA", "SHIRALA"),
#     ("RATNAGIRI", "RATNAGIRI"),
#     ("MAYANI", "MAYANI"),
#     ("SOLAPUR_1", "SOLAPUR_1"),
#     ("SOLAPUR_2", "SOLAPUR_2"),
#     ("SOLAPUR_3", "SOLAPUR_3"),
#     ("PARANDA", "PARANDA"),
#     ("MURUD", "MURUD"),
#     ("KONDHWA", "KONDHWA"),
#     ("KARVENAGAR", "KARVENAGAR"),
#     ("PUNE_1", "PUNE_1"),
#     ("PUNE_2", "PUNE_2"),
#     ("PUNE_3", "PUNE_3"),
#     ("PIMPRICHINCHWAD", "PIMPRICHINCHWAD"),
#     ("SHELARWADI", "SHELARWADI"),
#     ("AHMADPUR", "AHMADPUR"),
#     ("KOPRA", "KOPRA"),
#     ("APOLLOBANDARCOLABA", "APOLLOBANDARCOLABA"),
#     ("NAVIMUMBAI", "NAVIMUMBAI"),
#     ("PANVEL", "PANVEL"),
#     ("MUMBAI_1", "MUMBAI_1"),
#     ("TURBHE", "TURBHE"),
#     ("TALOJA", "TALOJA"),
#     ("MUMBAI_2", "MUMBAI_2"),
#     ("MUMBAI_3", "MUMBAI_3"),
#     ("MUMBAI_4", "MUMBAI_4"),
#     ("THANE_1", "THANE_1"),
#     ("MUMBAI_5", "MUMBAI_5"),
#     ("DAMRANCHA", "DAMRANCHA"),
#     ("THANE_2", "THANE_2"),
#     ("PATHRI", "PATHRI"),
#     ("THANE_3", "THANE_3"),
#     ("KALYAN", "KALYAN"),
#     ("NAIGAON", "NAIGAON"),
#     ("NASHIK_1", "NASHIK_1"),
#     ("KOLTHAN", "KOLTHAN"),
#     ("NASHIK_2", "NASHIK_2"),
#     ("JATWADA", "JATWADA"),
#     ("NASHIK_3", "NASHIK_3"),
#     ("ARNI", "ARNI"),
#     ("MEHKAR", "MEHKAR"),
#     ("SINDEWAHI", "SINDEWAHI"),
#     ("NANDGAON", "NANDGAON"),
#     ("YAVATMAL", "YAVATMAL"),
#     ("GHATNANDRA", "GHATNANDRA"),
#     ("HINGANGHAT", "HINGANGHAT"),
#     ("DATTAPURDHAMANGAON", "DATTAPURDHAMANGAON"),
#     ("MALKAPUR", "MALKAPUR"),
#     ("AMRAVATI", "AMRAVATI"),
#     ("NAGPUR_1", "NAGPUR_1"),
#     ("KAMPTEE", "KAMPTEE"),
#     ("NAGPUR_2", "NAGPUR_2"),
#     ("AMGAONKH.", "AMGAONKH."),
#     ("WARLA", "WARLA"),
#     ("NARKHED", "NARKHED"),
#     ("TOLBUNG", "TOLBUNG"),
#     ("NAMBASHIKHULLEN", "NAMBASHIKHULLEN"),
#     ("JATRAKONA-II", "JATRAKONA-II"),
#     ("UMLŽ?REM", "UMLŽ?REM"),
#     ("KHANAPARA", "KHANAPARA"),
#     ("ZUNHEBOTO", "ZUNHEBOTO"),
#     ("KADAGUDA", "KADAGUDA"),
#     ("DIGAPAHANDI", "DIGAPAHANDI"),
#     ("CHANDRAPUR", "CHANDRAPUR"),
#     ("KHALIKOTE", "KHALIKOTE"),
#     ("CHILIKANUAPADA", "CHILIKANUAPADA"),
#     ("KOKSARA", "KOKSARA"),
#     ("JUNAGARH", "JUNAGARH"),
#     ("RAIGHAR", "RAIGHAR"),
#     ("BHOGARA", "BHOGARA"),
#     ("BOIRGAON", "BOIRGAON"),
#     ("BHINGARPUR", "BHINGARPUR"),
#     ("BHUASUNI", "BHUASUNI"),
#     ("CUTTACK", "CUTTACK"),
#     ("NARASINGHPUR", "NARASINGHPUR"),
#     ("PURUNAKOT", "PURUNAKOT"),
#     ("DEULDUNGURI", "DEULDUNGURI"),
#     ("PATNAGARH", "PATNAGARH"),
#     ("GARHAPARAJANG", "GARHAPARAJANG"),
#     ("DANGAPAL", "DANGAPAL"),
#     ("CHHENDIPADA", "CHHENDIPADA"),
#     ("ANANDAPURPART", "ANANDAPURPART"),
#     ("REAMAL", "REAMAL"),
#     ("SAMBALPUR", "SAMBALPUR"),
#     ("AHARAPADA", "AHARAPADA"),
#     ("SARGIDIHI", "SARGIDIHI"),
#     ("BADHUNIA", "BADHUNIA"),
#     ("ROURKELA", "ROURKELA"),
#     ("NETTAPAKKAM", "NETTAPAKKAM"),
#     ("KUNICHAMPET", "KUNICHAMPET"),
#     ("YANAM", "YANAM"),
#     ("MOONAK", "MOONAK"),
#     ("LEHRI", "LEHRI"),
#     ("MALOUT", "MALOUT"),
#     ("CHAURA", "CHAURA"),
#     ("FAZILKA", "FAZILKA"),
#     ("MALERKOTLA", "MALERKOTLA"),
#     ("KOTKAPURA", "KOTKAPURA"),
#     ("SASNAGAR(MOHALI)_1", "SASNAGAR(MOHALI)_1"),
#     ("SASNAGAR(MOHALI)_2", "SASNAGAR(MOHALI)_2"),
#     ("FOCALPOINT", "FOCALPOINT"),
#     ("INDUSTRIALZONE", "INDUSTRIALZONE"),
#     ("FIROZPUR", "FIROZPUR"),
#     ("GARHSHANKAR", "GARHSHANKAR"),
#     ("CHHOTIBARANDARII", "CHHOTIBARANDARII"),
#     ("HUSSAINPUR", "HUSSAINPUR"),
#     ("BASTIBAWAKHEL", "BASTIBAWAKHEL"),
#     ("SULTANWIND", "SULTANWIND"),
#     ("CHHEHARTA", "CHHEHARTA"),
#     ("AJNALA", "AJNALA"),
#     ("DERABABANANAK", "DERABABANANAK"),
#     ("MARARA", "MARARA"),
#     ("SAJJANGARH", "SAJJANGARH"),
#     ("KOTRI", "KOTRI"),
#     ("RISHABHDEO", "RISHABHDEO"),
#     ("DHARIAWAD", "DHARIAWAD"),
#     ("PIRAWA", "PIRAWA"),
#     ("PHALASIYA", "PHALASIYA"),
#     ("SARDA DUNGAR GARH", "SARDA DUNGAR GARH"),
#     ("ABUROAD", "ABUROAD"),
#     ("ASNAWAR", "ASNAWAR"),
#     ("SUKHER", "SUKHER"),
#     ("KANERA", "KANERA"),
#     ("JALBERI", "JALBERI"),
#     ("BARAN", "BARAN"),
#     ("SHRINATHPURAM", "SHRINATHPURAM"),
#     ("KANSUWA", "KANSUWA"),
#     ("SUMERPUR", "SUMERPUR"),
#     ("GUDHAMALANI", "GUDHAMALANI"),
#     ("BAGODA", "BAGODA"),
#     ("GANGAPUR", "GANGAPUR"),
#     ("RAILWAYSTATIONAREA", "RAILWAYSTATIONAREA"),
#     ("MANDALGARH", "MANDALGARH"),
#     ("SHAHPURA_1", "SHAHPURA_1"),
#     ("SIWANA", "SIWANA"),
#     ("RAMA", "RAMA"),
#     ("DEI", "DEI"),
#     ("MARWARJUNCTION", "MARWARJUNCTION"),
#     ("ASIND", "ASIND"),
#     ("GADRAROAD", "GADRAROAD"),
#     ("BARMER", "BARMER"),
#     ("PANCHLA", "PANCHLA"),
#     ("KHANDAR", "KHANDAR"),
#     ("KALYANPUR", "KALYANPUR"),
#     ("MANPURAKHARDA", "MANPURAKHARDA"),
#     ("JOGIDASKAGAON", "JOGIDASKAGAON"),
#     ("MALPURA", "MALPURA"),
#     ("BONLI", "BONLI"),
#     ("SINDHIPURA", "SINDHIPURA"),
#     ("BEENJOTA", "BEENJOTA"),
#     ("HATHIKHERA", "HATHIKHERA"),
#     ("SARMATHURA", "SARMATHURA"),
#     ("GHOOGHRA", "GHOOGHRA"),
#     ("LOONAR", "LOONAR"),
#     ("PHAGI", "PHAGI"),
#     ("NADOTI", "NADOTI"),
#     ("DECHOO", "DECHOO"),
#     ("JEEROTA", "JEEROTA"),
#     ("ROOPANGARH", "ROOPANGARH"),
#     ("KANOI", "KANOI"),
#     ("KISHANPURAATLALWAS", "KISHANPURAATLALWAS"),
#     ("KUCHERA", "KUCHERA"),
#     ("SHAHGARH", "SHAHGARH"),
#     ("BHARATPUR", "BHARATPUR"),
#     ("GUWARA SOTI", "GUWARA SOTI"),
#     ("AAU", "AAU"),
#     ("NADBAI", "NADBAI"),
#     ("JAYAL", "JAYAL"),
#     ("RAJGARH", "RAJGARH"),
#     ("DANTARAMGARH", "DANTARAMGARH"),
#     ("NAGAUR", "NAGAUR"),
#     ("SHAHPURA_2", "SHAHPURA_2"),
#     ("DIDWANA", "DIDWANA"),
#     ("SHRIMADHOPUR", "SHRIMADHOPUR"),
#     ("LONGEWALA", "LONGEWALA"),
#     ("SUTHAR MANDI", "SUTHAR MANDI"),
#     ("NOKHA", "NOKHA"),
#     ("KAMAN", "KAMAN"),
#     ("NECHHWA", "NECHHWA"),
#     ("NAWALGARH", "NAWALGARH"),
#     ("MUNDAWAR", "MUNDAWAR"),
#     ("KISHANGARH", "KISHANGARH"),
#     ("RANJITPURA", "RANJITPURA"),
#     ("BIWANDI", "BIWANDI"),
#     ("ROOPNAGAR", "ROOPNAGAR"),
#     ("SURAJGARH", "SURAJGARH"),
#     ("SOMASAR", "SOMASAR"),
#     ("LUNKARANSAR", "LUNKARANSAR"),
#     ("RANISAR", "RANISAR"),
#     ("RAWLAMANDI", "RAWLAMANDI"),
#     ("NOHAR", "NOHAR"),
#     ("ANUPGARH", "ANUPGARH"),
#     ("SURATGARH", "SURATGARH"),
#     ("UMEWALA", "UMEWALA"),
#     ("SRIGANGANAGAR", "SRIGANGANAGAR"),
#     ("NAMCHI", "NAMCHI"),
#     ("RESHI", "RESHI"),
#     ("DENTAM", "DENTAM"),
#     ("YANGYANG", "YANGYANG"),
#     ("KUPUP", "KUPUP"),
#     ("LACHEN", "LACHEN"),
#     ("THANGU VALLEY", "THANGU VALLEY"),
#     ("THOOTHUKUDI_1", "THOOTHUKUDI_1"),
#     ("THOOTHUKUDI_2", "THOOTHUKUDI_2"),
#     ("THIRUPARANKUNDRAM", "THIRUPARANKUNDRAM"),
#     ("MADURAI_1", "MADURAI_1"),
#     ("MADURAI_2", "MADURAI_2"),
#     ("MADURAI_3", "MADURAI_3"),
#     ("DINDIGUL_1", "DINDIGUL_1"),
#     ("DINDIGUL_2", "DINDIGUL_2"),
#     ("DINDIGUL_3", "DINDIGUL_3"),
#     ("TIRUCHIRAPPALLI_1", "TIRUCHIRAPPALLI_1"),
#     ("THANJAVUR_1", "THANJAVUR_1"),
#     ("THANJAVUR_2", "THANJAVUR_2"),
#     ("THANJAVUR_3", "THANJAVUR_3"),
#     ("THIRUVERUMBUR", "THIRUVERUMBUR"),
#     ("TIRUCHIRAPPALLI_2", "TIRUCHIRAPPALLI_2"),
#     ("PODANUR", "PODANUR"),
#     ("COIMBATORE_1", "COIMBATORE_1"),
#     ("COIMBATORE_2", "COIMBATORE_2"),
#     ("ARULPURAM", "ARULPURAM"),
#     ("COIMBATORE_3", "COIMBATORE_3"),
#     ("TIRUPPUR_1", "TIRUPPUR_1"),
#     ("TIRUPPUR_2", "TIRUPPUR_2"),
#     ("TIRUPPUR_3", "TIRUPPUR_3"),
#     ("ERODE_1", "ERODE_1"),
#     ("ERODE_2", "ERODE_2"),
#     ("PALLIPALAYAM", "PALLIPALAYAM"),
#     ("SALEM_1", "SALEM_1"),
#     ("SALEM_2", "SALEM_2"),
#     ("SALEM_3", "SALEM_3"),
#     ("VELLORE_1", "VELLORE_1"),
#     ("VELLORE_2", "VELLORE_2"),
#     ("KARAPAKKAM", "KARAPAKKAM"),
#     ("VELLORE_3", "VELLORE_3"),
#     ("TAMBARAM", "TAMBARAM"),
#     ("VELLORE_4", "VELLORE_4"),
#     ("ANNANUR", "ANNANUR"),
#     ("VALLUR", "VALLUR"),
#     ("AIZA", "AIZA"),
#     ("YERRUPALEM", "YERRUPALEM"),
#     ("GARIDEPALLI", "GARIDEPALLI"),
#     ("KURMALGUDA", "KURMALGUDA"),
#     ("RAJENDRANAGARMANDAL", "RAJENDRANAGARMANDAL"),
#     ("HAYATNAGAR_1", "HAYATNAGAR_1"),
#     ("MARIPEDA", "MARIPEDA"),
#     ("GUMMADIVALLI", "GUMMADIVALLI"),
#     ("HYDERABAD_1", "HYDERABAD_1"),
#     ("SECUNDERABAD_1", "SECUNDERABAD_1"),
#     ("HYDERABAD_2", "HYDERABAD_2"),
#     ("KAREPALLI", "KAREPALLI"),
#     ("SECUNDERABAD_2", "SECUNDERABAD_2"),
#     ("ZAHIRABAD", "ZAHIRABAD"),
#     ("KOTHAGUDA", "KOTHAGUDA"),
#     ("KHAZIPET", "KHAZIPET"),
#     ("WARANGAL", "WARANGAL"),
#     ("HANUMAKONDA_1", "HANUMAKONDA_1"),
#     ("HANUMAKONDA_2", "HANUMAKONDA_2"),
#     ("KANGTI", "KANGTI"),
#     ("KARIMNAGAR_1", "KARIMNAGAR_1"),
#     ("KARIMNAGAR_2", "KARIMNAGAR_2"),
#     ("MANTHANI", "MANTHANI"),
#     ("KAMMARPALLI", "KAMMARPALLI"),
#     ("DANDEPALLI", "DANDEPALLI"),
#     ("LINGAPUR", "LINGAPUR"),
#     ("SIRIKONDA", "SIRIKONDA"),
#     ("KAILASHAHAR", "KAILASHAHAR"),
#     ("RAJAPUR", "RAJAPUR"),
#     ("VARANASI_1", "VARANASI_1"),
#     ("MUGHALSARAI", "MUGHALSARAI"),
#     ("VARANASI_2", "VARANASI_2"),
#     ("SADWAKALAN", "SADWAKALAN"),
#     ("VARANASI_3", "VARANASI_3"),
#     ("CHEDIBEER", "CHEDIBEER"),
#     ("PRAYAGRAJ", "PRAYAGRAJ"),
#     ("NAGRA", "NAGRA"),
#     ("KABIRNAGAR", "KABIRNAGAR"),
#     ("JHANSI", "JHANSI"),
#     ("OLDKATRA", "OLDKATRA"),
#     ("BABERU", "BABERU"),
#     ("GARSARI", "GARSARI"),
#     ("MEHNAGAR", "MEHNAGAR"),
#     ("MANIRAMPUR", "MANIRAMPUR"),
#     ("PATTI", "PATTI"),
#     ("JAMINKAKARGHATTI", "JAMINKAKARGHATTI"),
#     ("SHAHGANJ", "SHAHGANJ"),
#     ("ATRAULIA", "ATRAULIA"),
#     ("MANPUR", "MANPUR"),
#     ("RAMPURA", "RAMPURA"),
#     ("NAUBASTA", "NAUBASTA"),
#     ("JAJMAU", "JAJMAU"),
#     ("PANKI", "PANKI"),
#     ("CIVILLINES", "CIVILLINES"),
#     ("UTELA", "UTELA"),
#     ("NAWABGANJ", "NAWABGANJ"),
#     ("BARAULIKHALILABAD", "BARAULIKHALILABAD"),
#     ("KHALILABAD", "KHALILABAD"),
#     ("BAIRIALIPUR", "BAIRIALIPUR"),
#     ("LUCKNOW", "LUCKNOW"),
#     ("DAULATGANJ", "DAULATGANJ"),
#     ("BARABANKI", "BARABANKI"),
#     ("MUDIYAR", "MUDIYAR"),
#     ("MOYAIYANPUR", "MOYAIYANPUR"),
#     ("DOMARIYAGANJ", "DOMARIYAGANJ"),
#     ("SURUCHIPURAMCOLONY", "SURUCHIPURAMCOLONY"),
#     ("AGRA", "AGRA"),
#     ("MAHMUDABAD", "MAHMUDABAD"),
#     ("AKBARPURAUNCHHA", "AKBARPURAUNCHHA"),
#     ("NAUTANWA", "NAUTANWA"),
#     ("GOPALPUR", "GOPALPUR"),
#     ("PACHPERWA", "PACHPERWA"),
#     ("GOPAMAU", "GOPAMAU"),
#     ("BAMHNAWA", "BAMHNAWA"),
#     ("SIKANDRARAO", "SIKANDRARAO"),
#     ("BHINGA", "BHINGA"),
#     ("DHANIPUR", "DHANIPUR"),
#     ("DHAURRAMAFI", "DHAURRAMAFI"),
#     ("RANJITGARHI", "RANJITGARHI"),
#     ("BUDAUN", "BUDAUN"),
#     ("NIGOHI", "NIGOHI"),
#     ("HARKHAPUR", "HARKHAPUR"),
#     ("KHURJA", "KHURJA"),
#     ("AONLA", "AONLA"),
#     ("BHIRA", "BHIRA"),
#     ("PATELBIHARCOLONY", "PATELBIHARCOLONY"),
#     ("GREATERNOIDA", "GREATERNOIDA"),
#     ("CHANDANCHAUKI", "CHANDANCHAUKI"),
#     ("NOIDA", "NOIDA"),
#     ("PILIBHIT", "PILIBHIT"),
#     ("GHAZIABAD", "GHAZIABAD"),
#     ("HASANPUR", "HASANPUR"),
#     ("TASHKA", "TASHKA"),
#     ("HAYATNAGAR_2", "HAYATNAGAR_2"),
#     ("LALIYANA", "LALIYANA"),
#     ("BAGPAT", "BAGPAT"),
#     ("BIJNOR", "BIJNOR"),
#     ("SHAMLI", "SHAMLI"),
#     ("SAHARANPUR_1", "SAHARANPUR_1"),
#     ("SAHARANPUR_2", "SAHARANPUR_2"),
#     ("SAHARANPUR_3", "SAHARANPUR_3"),
#     ("JHALAKUDI", "JHALAKUDI"),
#     ("BHINGRADRANGE", "BHINGRADRANGE"),
#     ("KALAGARH", "KALAGARH"),
#     ("NAINIDANDA", "NAINIDANDA"),
#     ("DHARCHULA", "DHARCHULA"),
#     ("TEEJAM", "TEEJAM"),
#     ("BHARARISAIN", "BHARARISAIN"),
#     ("KALAPANI", "KALAPANI"),
#     ("DEHRADUN_1", "DEHRADUN_1"),
#     ("DEHRADUN_2", "DEHRADUN_2"),
#     ("KUTI", "KUTI"),
#     ("DEHRADUN_3", "DEHRADUN_3"),
#     ("DEHRADUN_4", "DEHRADUN_4"),
#     ("KEDARNATH", "KEDARNATH"),
#     ("BADRINATH", "BADRINATH"),
#     ("GANGOTRI", "GANGOTRI"),
#     ("BAKKHALI", "BAKKHALI"),
#     ("BALIGERIA", "BALIGERIA"),
#     ("HALDIA", "HALDIA"),
#     ("RAJPURSONARPUR", "RAJPURSONARPUR"),
#     ("PURBAPUTIARY", "PURBAPUTIARY"),
#     ("PUJALI", "PUJALI"),
#     ("MAHESHTALA", "MAHESHTALA"),
#     ("KGHODHATI", "KGHODHATI"),
#     ("KOLKATA", "KOLKATA"),
#     ("RAJARHAT", "RAJARHAT"),
#     ("HOWRAH_1", "HOWRAH_1"),
#     ("HOWRAH_2", "HOWRAH_2"),
#     ("MADHYAMGRAM", "MADHYAMGRAM"),
#     ("RAJYADHARPUR", "RAJYADHARPUR"),
#     ("BAGHMUNDI", "BAGHMUNDI"),
#     ("MAJHDIA", "MAJHDIA"),
#     ("BAMUNARA", "BAMUNARA"),
#     ("DURGAPUR_1", "DURGAPUR_1"),
#     ("DURGAPUR_2", "DURGAPUR_2"),
#     ("BETAI", "BETAI"),
#     ("KHARIBONA", "KHARIBONA"),
#     ("RAGHUNATHGANJ", "RAGHUNATHGANJ"),
#     ("KALIACHAK", "KALIACHAK"),
#     ("BARTALI", "BARTALI"),
#     ("KUMARGANJ", "KUMARGANJ"),
#     ("KALIYAGANJ", "KALIYAGANJ"),
#     ("ISLAMPUR", "ISLAMPUR"),
#     ("HALDIBARI", "HALDIBARI"),
#     ("KUMARGRAM", "KUMARGRAM"),
#     ("JAIGAON", "JAIGAON"),
#     ("SUKHANIBASTI", "SUKHANIBASTI"),
# ]

# print(len(STATION_CHOICES))

import pandas as pd
from yourapp.models import State, District, SubDistrict, Town

file_path = "Priority 1_CORS Densification (5).xlsx"

df = pd.read_excel(file_path)
df.columns = df.columns.str.strip()

for _, row in df.iterrows():

    state_name = str(row["STATE_UT"]).strip()
    district_name = str(row["DISTRICT"]).strip()
    subdistrict_name = str(row["SUBDISTRICT"]).strip()
    town_name = str(row["TOWN"]).strip()

    # Get latitude & longitude (handle blank safely)
    state_lat = row.get("LATITUDE")
    state_lon = row.get("LONGITUDE")

    # 1️⃣ Create or Update State with lat/long
    state_obj, created = State.objects.get_or_create(
        name=state_name,
        defaults={
            "latitude": state_lat,
            "longitude": state_lon
        }
    )

    # If state already exists but lat/long empty, update it
    if not created:
        if not state_obj.latitude:
            state_obj.latitude = state_lat
        if not state_obj.longitude:
            state_obj.longitude = state_lon
        state_obj.save()

    # 2️⃣ District
    district_obj, _ = District.objects.get_or_create(
        state=state_obj,
        name=district_name
    )

    # 3️⃣ SubDistrict
    subdistrict_obj, _ = SubDistrict.objects.get_or_create(
        district=district_obj,
        name=subdistrict_name
    )

    # 4️⃣ Town
    Town.objects.create(
        subdistrict=subdistrict_obj,
        base_name=town_name
    )

print("✅ All data including State lat/long saved successfully")
