# Generated by Django 5.2.9 on 2026-02-05 08:04

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile", models.CharField(max_length=10)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SURVEYOR", "Surveyor"),
                            ("SUPERVISOR", "Supervisor"),
                            ("DIRECTOR", "Director"),
                            ("ZONAL_CHIEF", "Zonal Chief"),
                            ("GNRB", "GNRB Authority"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORTH", "North"),
                            ("SOUTH", "South"),
                            ("EAST", "East"),
                            ("WEST", "West"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("SUPERVISOR_APPROVED", "Supervisor Approved"),
                            ("DIRECTOR_APPROVED", "Director Approved"),
                            ("ZONAL_CHIEF_APPROVED", "Zonal Chief Approved"),
                            ("GNRB_APPROVED", "GNRB Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "surveyor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval_level",
                    models.IntegerField(
                        choices=[
                            (1, "Supervisor"),
                            (2, "Director"),
                            (3, "Zonal Chief"),
                            (4, "GNRB"),
                        ]
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField()),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveySubSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subsite_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsites",
                        to="survey_app.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveySkyVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obstruction_data",
                    models.JSONField(
                        help_text="add the lan,long and vertical angel obstruction data here"
                    ),
                ),
                ("multipath_risk", models.BooleanField()),
                ("emi_sources", models.TextField()),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app.surveysubsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ac_grid", models.BooleanField()),
                ("solar_possible", models.BooleanField()),
                ("sun_hours", models.IntegerField()),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app.surveysubsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("north_photo", models.ImageField(upload_to="survey_photos/")),
                ("east_photo", models.ImageField(upload_to="survey_photos/")),
                ("south_photo", models.ImageField(upload_to="survey_photos/")),
                ("west_photo", models.ImageField(upload_to="survey_photos/")),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sub_site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="survey_app.surveysubsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyMonument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monument_type",
                    models.CharField(
                        choices=[("GROUND", "Ground"), ("ROOFTOP", "Rooftop")],
                        max_length=10,
                    ),
                ),
                ("building_stories", models.IntegerField(blank=True, null=True)),
                ("accessibility", models.TextField()),
                ("surroundings", models.TextField()),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app.surveysubsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app.surveysubsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyConnectivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gsm_4g", models.BooleanField()),
                ("broadband", models.BooleanField()),
                ("fiber", models.BooleanField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app.surveysubsite",
                    ),
                ),
            ],
        ),
    ]
