# Generated by Django 5.2.9 on 2026-02-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statedb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "state",
            },
        ),
        migrations.CreateModel(
            name="Districtdb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="survey_app.state",
                    ),
                ),
            ],
            options={
                "db_table": "district",
                "unique_together": {("state", "name")},
            },
        ),
        migrations.CreateModel(
            name="Towndb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_no", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("height", models.FloatField(blank=True, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="towns",
                        to="survey_app.district",
                    ),
                ),
            ],
            options={
                "db_table": "town",
                "unique_together": {("district", "name")},
            },
        ),
    ]
