# Generated by Django 5.2.11 on 2026-02-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveysubsite",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="Priority of subsite (lower number = higher priority)",
                unique=True,
            ),
        ),
    ]
