# Generated by Django 5.2.9 on 2026-02-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveypower",
            old_name="sun_hours",
            new_name="solar_exposure_hours",
        ),
    ]
