# Generated by Django 5.2.9 on 2026-02-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyskyvisibility",
            name="multipath_emi_other",
        ),
        migrations.RemoveField(
            model_name="surveyskyvisibility",
            name="obstruction_data",
        ),
    ]
