# Generated by Django 5.2.11 on 2026-02-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0002_alter_surveysubsite_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveysubsite",
            name="priority",
            field=models.IntegerField(
                help_text="Priority of subsite (lower number = higher priority)"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveysubsite",
            constraint=models.UniqueConstraint(
                fields=("survey", "priority"), name="unique_priority_per_survey"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveysubsite",
            constraint=models.UniqueConstraint(
                fields=("survey", "location"), name="unique_location_per_survey"
            ),
        ),
    ]
