# Generated by Django 5.2.9 on 2026-02-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0002_statedb_districtdb_towndb"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtdb",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="districtdb",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statedb",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statedb",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Stationdb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_no", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("height", models.FloatField(blank=True, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="survey_app.district",
                    ),
                ),
            ],
            options={
                "db_table": "station",
                "unique_together": {("district", "name")},
            },
        ),
        migrations.DeleteModel(
            name="Towndb",
        ),
    ]
