# Generated by Django 5.2.11 on 2026-02-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0003_alter_surveysubsite_priority_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="surveysubsite",
            name="unique_priority_per_survey",
        ),
        migrations.RemoveConstraint(
            model_name="surveysubsite",
            name="unique_location_per_survey",
        ),
        migrations.AlterField(
            model_name="surveysubsite",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="Priority of subsite (lower number = higher priority)",
            ),
        ),
    ]
