# Generated by Django 5.2.9 on 2026-02-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0003_districtdb_latitude_districtdb_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stationdb",
            name="code",
        ),
        migrations.RemoveField(
            model_name="stationdb",
            name="sl_no",
        ),
    ]
