# Generated by Django 5.2.9 on 2026-03-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0004_remove_surveysubsite_unique_priority_per_survey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveysubsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("SUPERVISOR_APPROVED", "Supervisor Approved"),
                    ("DIRECTOR_APPROVED", "Director Approved"),
                    ("REJECTED_BY_DIRECTOR", "Rejected by Director"),
                    ("SENT_TO_ZONAL", "Sent to Zonal Chief"),
                    ("REJECTED_BY_ZONAL", "Rejected by Zonal Chief"),
                    ("ZONAL_APPROVED", "Zonal Chief Approved"),
                    ("SENT_TO_GNRB", "Sent to GNRB"),
                    ("REJECTED_BY_GNRB", "Rejected by GNRB"),
                    ("FINAL_APPROVED", "Final Approved"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
    ]
