# Generated by Django 5.2.9 on 2026-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0004_remove_stationdb_code_remove_stationdb_sl_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationdb",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stationdb",
            name="sl_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
