# Generated by Django 5.2.9 on 2026-03-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0005_surveysubsite_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyapproval",
            name="subsite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey_app.surveysubsite",
            ),
        ),
    ]
