# Generated by Django 5.2.9 on 2026-02-21 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0005_stationdb_code_stationdb_sl_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="districtdb",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="survey_app.statedb",
            ),
        ),
        migrations.AlterField(
            model_name="stationdb",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stations",
                to="survey_app.districtdb",
            ),
        ),
    ]
