# Generated by Django 5.2.9 on 2026-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0006_surveyapproval_subsite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
