# Generated by Django 5.0.6 on 2026-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubsite',
            name='contact_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
