# Generated by Django 5.2.9 on 2026-03-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0007_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="director",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "DIRECTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
