# Generated by Django 5.2.9 on 2026-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0008_user_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveylocation",
            name="state",
            field=models.CharField(
                choices=[
                    ("ANDHRA_PRADESH", "Andhra Pradesh"),
                    ("ARUNACHAL_PRADESH", "Arunachal Pradesh"),
                    ("ASSAM", "Assam"),
                    ("BIHAR", "Bihar"),
                    ("CHHATTISGARH", "Chhattisgarh"),
                    ("GOA", "Goa"),
                    ("GUJARAT", "Gujarat"),
                    ("HARYANA", "Haryana"),
                    ("HIMACHAL_PRADESH", "Himachal Pradesh"),
                    ("JHARKHAND", "Jharkhand"),
                    ("KARNATAKA", "Karnataka"),
                    ("KERALA", "Kerala"),
                    ("MADHYA_PRADESH", "Madhya Pradesh"),
                    ("MAHARASHTRA", "Maharashtra"),
                    ("MANIPUR", "Manipur"),
                    ("MEGHALAYA", "Meghalaya"),
                    ("MIZORAM", "Mizoram"),
                    ("NAGALAND", "Nagaland"),
                    ("ODISHA", "Odisha"),
                    ("PUNJAB", "Punjab"),
                    ("RAJASTHAN", "Rajasthan"),
                    ("SIKKIM", "Sikkim"),
                    ("TAMIL_NADU", "Tamil Nadu"),
                    ("TELANGANA", "Telangana"),
                    ("TRIPURA", "Tripura"),
                    ("UTTAR_PRADESH", "Uttar Pradesh"),
                    ("UTTARAKHAND", "Uttarakhand"),
                    ("WEST_BENGAL", "West Bengal"),
                    ("ANDAMAN_NICOBAR", "Andaman and Nicobar Islands"),
                    ("CHANDIGARH", "Chandigarh"),
                    (
                        "DADRA_NAGAR_HAVELI_DAMAN_DIU",
                        "Dadra and Nagar Haveli and Daman and Diu",
                    ),
                    ("DELHI", "Delhi"),
                    ("JAMMU_KASHMIR", "Jammu and Kashmir"),
                    ("LADAKH", "Ladakh"),
                    ("LAKSHADWEEP", "Lakshadweep"),
                    ("PUDUCHERRY", "Puducherry"),
                ],
                max_length=50,
            ),
        ),
    ]
