# Generated by Django 5.2.9 on 2026-03-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0009_alter_surveylocation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveysubsite",
            name="noc",
            field=models.FileField(blank=True, null=True, upload_to="noc_documents/"),
        ),
        migrations.AddField(
            model_name="surveysubsite",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveylocation",
            name="state",
            field=models.CharField(max_length=100),
        ),
    ]
